# Generated by Django 5.2.9 on 2026-01-06 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.TextField(help_text='Main reason for visit')),
                ('symptoms', models.TextField(help_text='Symptoms reported by patient')),
                ('diagnosis', models.TextField(help_text="Doctor's diagnosis")),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate (bpm)', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature (°C)', max_digits=4, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Respiratory rate (breaths/min)', null=True)),
                ('doctor_notes', models.TextField(blank=True, help_text='Additional notes from doctor', null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Recommended treatment plan', null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended follow-up date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 10ml', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., twice daily, every 8 hours', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 7 days, 2 weeks', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for taking medication', null=True)),
                ('has_allergy_alert', models.BooleanField(default=False)),
                ('allergy_alert_message', models.TextField(blank=True, null=True)),
                ('has_conflict_alert', models.BooleanField(default=False)),
                ('conflict_alert_message', models.TextField(blank=True, null=True)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.medicalvisit')),
            ],
            options={
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['patient', '-visit_date'], name='medical_med_patient_efe5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['doctor', '-visit_date'], name='medical_med_doctor__4fd0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-prescribed_date'], name='medical_pre_patient_c26422_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['medication_name'], name='medical_pre_medicat_e4ca38_idx'),
        ),
    ]
